apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dallecool
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: dallecool
spec:
  source:
    git:
      url: https://github.com/alexandreroman/dallecool
      ref:
        branch: testing
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  serviceClaims:
  - name: openai
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: openai-claim
